container:
  image: gradle:4.3-jdk8

check_task:
  gradle_cache:
    folder: ~/.gradle/caches
  check_script: gradle check
  cleanup_before_cache_script:
    - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
    - rm -f ~/.gradle/caches/user-id.txt
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete